### PR TITLE
feat: Switching to new naming convention `sd-setup-*` for startup commands [minor]

### PR DESCRIPTION
**Pull request by stjohnjohnson**
In the API we're naming all setup steps with `sd-setup-`

PRs needed:
 - https://github.com/screwdriver-cd/build-bookend/pull/4
 - https://github.com/screwdriver-cd/models/pull/143

### CODE REVIEW

**Comment by d2lam** [comment]
Don't you need to change models too?

**Comment by stjohnjohnson** [comment]
Actually, I'd love to remove this completely if it's not helpful.  @jer do you remember why we have https://github.com/screwdriver-cd/launcher/blob/cecfa6009b4c289dd40581032e30f384998543ba/screwdriver/emitter.go#L73-L75

**Comment by tkyi** [comment]
Is this naming convention documented somewhere?

**Comment by d2lam** [comment]
@stjohnjohnson  It's to log the thing that's happening here: https://github.com/screwdriver-cd/launcher/blob/ad07ecf62879d49884e3bf99b64ee9530176258e/launch.go#L140-L223

Creating workspace and setting up environments don't belong to any steps. If we don't have it, then how do we log it?

**Comment by petey** [comment]
config-parser will also need updates to prevent a user from making a `setup-*` or `teardown-*` step. The parser only prevents `sd-*`.

https://github.com/screwdriver-cd/config-parser/blob/98f8b11dd67943d425d880afb80e94221a9d95b5/lib/phase/functional.js#L64-L69

**Pull request merged**
